name: Build Python Package

on:
  push:
    branches:
      - main
    tags:
      - '*'

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you want to use

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build the package
      run: python -m build

    - name: Upload .whl artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/*.whl
